### ISSUE TITLE
Plugin store gives a "Service not available" after installing a plugin with migrations

### ISSUE THREAD

**Issue by Rias500** [pixelandtonic/craftcom#28]
### Description
Craft gives a 503 "Service not available" after installing a plugin with migrations, probably because they're not automatically run after activating a plugin.

### Steps to reproduce

1. Install a plugin from the plugin store with migrations (XML Sitemap by Dolphiq)
2. See the error

### Additional info

- Craft version: 3 RC-3
- PHP version: 7.1

**Comment by brandonkelly** [comment]
Guessing this was meant for the https://github.com/craftcms/cms/ repo?

Still, I just tested and wasn't able to reproduce. When installing a plugin, Craft runs its install migration, and makes a record of all existing plugin migrations (as if they had been run), so that future requests won't think that any migrations are pending.
